package ru.monetarys.exceptions;

public enum TransferErrorCode {

    PAYER_ACCOUNT_NOT_VALID,
    PAYEE_GUID_NOT_VALID,
    PAYEE_ACC_ID_NOT_VALID,
    PAYEE_ACCOUNT_NOT_VALID,
    PAYEE_ACCOUNT_NOT_ALLOWED,
    PAYEE_CARD_NUMBER_NOT_VALID,
    PAYEE_PHONE_NOT_VALID,
    AMOUNT_NOT_VALID,
    MESSAGE_TO_PAYEE_NOT_VALID,
    INCORRECT_PAYER_ACCOUNT_STATUS,
    INCORRECT_PAYER_ACCOUNT_TYPE,
    INCORRECT_PAYER_ACCOUNT_CURRENCY,
    INCORRECT_PAYEE_ACCOUNT_STATUS,
    INCORRECT_PAYEE_ACCOUNT_TYPE,
    INCORRECT_PAYEE_ACCOUNT_CURRENCY,
    PAYEE_NOT_RESIDENT,
    PAYEE_NON_INDIVIDUAL,
    CURRENCIES_NOT_MATCHING,
    BALANCE_EXCEED;

}
